#!/bin/bash

shopt -s extglob

function connectMenu {
	echo -e "${GREEN}Connected to database '$1' successfully${RESET}"
	while true 
	do
		
		echo ""
		echo -e "${BG_MAGENTA}---- Table '$1' Menu ----${RESET}"
		echo ""
		echo -e "1 - ${CYAN}Create Table${RESET}"
		echo -e "2 - ${CYAN}List Table${RESET}"
		echo -e "3 - ${CYAN}Drop Table${RESET}"
		echo -e "4 - ${CYAN}Insert Into Table${RESET}"
		echo -e "5 - ${CYAN}Select From Table${RESET}"
		echo -e "6 - ${CYAN}Delete From Table${RESET}"
		echo -e "7 - ${CYAN}Update Table${RESET}"
		echo -e "8 - ${RED}Back To Main Menu${RESET}"
		echo ""
		read -r -p "Enter your choice(1-8) : " choice
		case $choice in
		"1")
			create_table
			;;
		"2")
			list_table
			;;
		"3")
			drop_table
			;;
		"4")
			insert_into_table
			;;
		"5")
			select_from_table
			;;
		"6")
			delete_from_table
			;;
		"7")
			update_table
			;;
		"8") 
			echo "Exiting..."; 
			clear
			break 
			;;
		*)
			echo -e "${RED}Invalid option${RESET}"
			;;
	 	esac
	done
}
