#!/bin/bash
function connect_DB {
	clear
	while true
	do
			echo ""
			echo -e "${MAGENTA}Available Databases :${RESET}"
			ls -1
			echo ""
			read -p "Please enter database name to connect(-1 to back to main menu): " DBName
			if [[ $DBName = -1 ]]
			then
				break
			fi
			
			if [[ -z "$DBName" ]]
			then
		    		echo -e "${RED}Database name cannot be empty. Please try again.${RESET}"
		    		continue
	       		fi
			
 			if [[ ! "$DBName" =~ ^[a-zA-Z0-9_]+$ ]]; then
    				echo -e "${RED}Error: Database name can only contain letters, numbers, and underscores.${RESET}"
    	 			continue
   			fi
			
			if [[ -e "$DBDIR/$DBName" ]]
			then
				cd "$DBDIR/$DBName"
				clear
				echo ""
				connectMenu $DBName
				break
			else
				echo -e "${YELLOW}Database '$DBName' does not exist.${RESET}"
			fi
	done
}
