#!/bin/bash


function connectMenu {
	echo "Connected to database '$1' successfully"
	while true 
	do
		
		echo ""
		echo "Database '$1' Options"
		echo ""
		echo "1 - Create Table"
		echo "2 - List Table"
		echo "3 - Drop Table"
		echo "4 - Insert Into Table"
		echo "5 - Select From Table"
		echo "6 - Delete From Table"
		echo "7 - Update Table"
		echo "8 - Back To Main Menu"
		echo ""
		read -r -p "Enter your choice(1-8) : " choice
		case $choice in
		"1")
			create_table
			;;
		"2")
			list_table
			;;
		"3")
			drop_table
			;;
		"4")
			insert_into_table
			;;
		"5")
			select_from_table
			;;
		"6")
			delete_from_table
			;;
		"7")
			update_table
			;;
		"8") 
			echo "Exiting..."; 
			break 
			;;
		*)
			echo "Invalid option"
			;;
	 	esac
	done
}
