#!/bin/bash
function delete_from_table {
	
	while true
	do
	ls -1;
	echo ""
        read -p "Enter table name (-1 to back to menu) : " TBName
        if [[ $TBName == -1 ]]; then
            break
        fi
	
	if [[ -z "$TBName" ]]
	then
		clear
		echo -e "${RED}Table name can't be empty. Please try again.${RESET}"
		continue
	fi
	
	if [[ ! "$TBName" =~ ^[a-zA-Z0-9_]+$ ]]
	then
		clear
		echo -e "${RED}Error: Table name can only contain letters, numbers and underscores.${RESET}"
		continue
	fi
	
	if [[ ! -e $TBName ]]; then
            echo -e "${YELLOW}Table '$TBName' does not exist!${RESET}"
            break;
        fi

        echo ""
        
         echo -e "${MAGENTA}Current Table Data:${RESET}"
         cat "$TBName" | tr ':' ' '
         echo ""
         echo -e "${BLUE}Notice That first column is the primary-key${RESET}"
         echo ""
         
         read -p "Enter primary key of the row you want to delete: " pk
         
         if grep -q "^$pk:" "$TBName"
	 then
	 	awk -F: -v pkey="$pk" '$1 != pkey' "$TBName" > temp && mv temp "$TBName"
         	echo -e "${GREEN}Line Deleted successfully${RESET}"
	 else
         	echo -e "${RED}Line not found${RESET}"
         fi
done
}
