#!/bin/bash
<<COMMENT
Asks for the table name
Finds the primary key column from the metadata.
Prompts the user to enter the primary key value to delete.
Checks if the record exists before attempting deletion.
Deletes the matching row using sed and confirms success
COMMENT
function delete_from_table {
	read -p "Enter table name" tName
	 
	
}
