#!/bin/bash

function drop_db {
	clear
	while true
	do
		echo ""
		echo -e "${CYAN}Available Databases :${RESET}"
		ls -1
		echo ""
		read -p "Enter Database name to drop (-1 to back to main menu) : " DBName
			if [[ $DBName = -1 ]]
			then
				break
			fi
			
			if [[ -z "$DBName" ]]
			then
		    		echo -e "${RED}Error, You've Entered Nothing !${RESET}"
		    		continue
	       		fi
			
 			if [[ ! "$DBName" =~ ^[a-zA-Z0-9_]+$ ]]; then
    				echo -e "${RED}Error, Database name only contain letters, numbers, and underscores.${RESET}"
    	 			continue
   			fi
			
			if [[ -e "$DBDIR/$DBName" ]]
			then
				rm -r $DBDIR/$DBName
				echo -e "${GREEN} Database '$DBName' Dropped Successfully${RESET}"
				break
			else
				echo -e "${RED}Database '$DBName' does not exist.${RESET}"
			fi
	done
}
