#!/bin/bash

function drop_db {
	clear
	while true
	do
		echo ""
		echo "Available Databases :"
		ls -1
		echo ""
		read -p "Enter Database name to drop (-1 to back to main menu) : " DBName
			if [[ $DBName = -1 ]]
			then
				break
			fi
			
			if [[ -z "$DBName" ]]
			then
		    		echo "Error, You've Entered Nothing !"
		    		continue
	       		fi
			
 			if [[ ! "$DBName" =~ ^[a-zA-Z0-9_]+$ ]]; then
    				echo "Error, Database name only contain letters, numbers, and underscores."
    	 			continue
   			fi
			
			if [[ -e "$DBDIR/$DBName" ]]
			then
				rm -r $DBDIR/$DBName
				echo " Database '$DBName' Dropped Successfully"
				break
			else
				echo "Database '$DBName' does not exist."
			fi
	done
}
