#!/bin/bash

function drop_table {
	if [[ ! "$(ls -1 "$DBDIR/$DBName")" ]]
	then
		clear
		echo -e "${YELLOW}Empty Database${RESET}"
		return
	fi	
	echo -e "${CYAN}Database Tables : ${RESET}"
	ls -1	
	read -p "Please enter table name: " tableName
	if [[ -e "$tableName" && -f $tableName ]]
	then 

		rm "$tableName"
		rm .$tableName-MetaData
		clear
		echo -e "${GREEN}Table '$tableName' dropped successfully.${RESET}"
	else
		clear
		echo -e "${RED}Error: Table '$tableName' does not exist.${RESET}"
	fi
}
