#!/bin/bash

function list_table {
	if [[ "$(ls -1 "$DBDIR/$DBName")" ]]
	then
		clear
		echo "Database Tables : "
		ls -1
		echo ""
		echo ""
	else
		clear
		echo ""
		echo "Database is Empty"
		echo ""
	fi
	
}
