#!/bin/bash

function list_table {
	if [[ "$(ls -1 "$DBDIR/$DBName")" ]]
	then
		clear
		echo -e "${UNDERLINE}${BLUE}Database Tables: ${RESET}"
		ls -1
		echo ""
	else
		clear
		echo ""
		echo -e "${YELLOW}Database is Empty${RESET}"
		echo ""
	fi
	
}
