#!/bin/bash

function select_from_table {
    if [[ ! -d "$DBDIR/$DBName" || -z "$(ls -A "$DBDIR/$DBName")" ]]; then
        clear
        echo -e "${YELLOW}Empty Database${RESET}"
        return
    fi    

    echo -e "${CYAN}Database Tables:${RESET}"
    ls -1 "$DBDIR/$DBName"  

    read -p "Enter table name (-1 to back to menu): " TBName

    if [[ $TBName == -1 ]]; then
        return
    fi

    if [[ ! -e "$TBName" ]]; then
        echo -e "${YELLOW}Table '$TBName' does not exist!${RESET}"
        return
    fi

    pkColumn=$(awk -F: '$1 == "pk" {print $2}' ".$TBName-MetaData")

    if [[ -z "$pkColumn" ]]; then
        echo -e "${RED}Error: No primary key found in metadata!${RESET}"
        return
    fi

    while true; do
        read -p "Enter the primary key value you want to select (-1 to cancel, * for all records): " PKValue

        if [[ $PKValue == -1 ]]; then
            return
        fi
        
        if [[ $PKValue == '*' ]]; then
            if [[ ! -s "$TBName" ]]; then
                echo -e "${RED}The table '$TBName' is empty.${RESET}"
            else
                echo -e "${BLUE}Displaying all records from '$TBName':${RESET}"
                cat "$TBName"
            fi
        else
            row=$(awk -F: -v pk="$PKValue" '$1 == pk {print $0}' "$TBName")

            if [[ -z "$row" ]]; then
                echo -e "${RED}No record found with $pkColumn = $PKValue.${RESET}"
            else
                echo -e "${GREEN}The data you selected is: ${row}${RESET}"
            fi
        fi
    done
}

